# Generated by Django 3.1.3 on 2021-06-19 05:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MAIL_SERVER_INFO',
            fields=[
                ('MAIL_SERVER_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('MAIL_SERVER_NAME', models.CharField(max_length=50)),
                ('IMAP_DOMAIN', models.CharField(max_length=100)),
                ('IMAP_PORT', models.IntegerField(max_length=100)),
                ('SMTP_DOMAIN', models.CharField(max_length=100)),
                ('SMTP_PORT', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SENTENCE',
            fields=[
                ('Category_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Upper_Category', models.TextField()),
                ('Lower_Category', models.TextField()),
                ('Sentence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('USER_ID', models.IntegerField(max_length=9, primary_key=True, serialize=False)),
                ('USER_EMAIL', models.CharField(max_length=200)),
                ('USER_PW', models.CharField(max_length=100)),
                ('USER_NAME', models.CharField(max_length=50)),
                ('USER_EMAIL_TYPE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_pj.mail_server_info')),
            ],
        ),
        migrations.CreateModel(
            name='USER_SIGN',
            fields=[
                ('SIGN_ID', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('SIGN_NAME', models.CharField(max_length=50)),
                ('SIGN_CONT', models.TextField()),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_pj.user')),
            ],
        ),
        migrations.CreateModel(
            name='ORDERS',
            fields=[
                ('MAIL_ID', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('RECEIVER_ADRESS', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('REFER_ADRESS', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('ME_FLAG', models.BooleanField(null=True)),
                ('TITLE', models.CharField(max_length=200)),
                ('CONTENT', models.TextField()),
                ('ATTACHMENTS', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), blank=True, size=None)),
                ('SEND_DT', models.DateTimeField(auto_now_add=True)),
                ('IMP_FLAG', models.BooleanField(null=True)),
                ('SENDER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_pj.user')),
            ],
        ),
        migrations.CreateModel(
            name='LOG',
            fields=[
                ('LOG_ID', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('LOG_TYPE', models.CharField(max_length=10)),
                ('DT', models.DateTimeField(auto_now_add=True)),
                ('STATUS', models.CharField(max_length=10)),
                ('DETAIL', models.TextField()),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_pj.user')),
            ],
        ),
        migrations.CreateModel(
            name='FILE',
            fields=[
                ('FILE_ID', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('UPLOAD_DT', models.DateTimeField(auto_now_add=True)),
                ('FILE_NAME', models.CharField(max_length=200)),
                ('FILE_PATH', models.TextField()),
                ('UPLOADER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_pj.user')),
            ],
        ),
    ]
